metadata:
  name: thi-generator
  labels:
    nuclio.io/project-name: eab0ff06-7945-4c15-b040-5f6be5c9af41
spec:
  handler: "main:handler"
  runtime: nodejs
  resources: {}
  image: "nuclio/processor-thi-generator:latest"
  minReplicas: 1
  maxReplicas: 1
  targetCPU: 75
  triggers:
    mqttTrigger:
      class: ""
      kind: mqtt
      url: "172.17.0.1:1883"
      username: admin
      password: admin
      attributes:
        subscriptions:
          - qos: 1
            topic: iot/logs
  version: 1
  build:
    functionSourceCode: dmFyIG1xdHQgPSByZXF1aXJlKCJtcXR0IiksIHVybCA9IHJlcXVpcmUoInVybCIpOw0KDQp2YXIgbXF0dF91cmwgPSB1cmwucGFyc2UoJ21xdHQ6Ly9hZG1pbjphZG1pbkAxNzIuMTcuMC4xOjE4ODMnKTsNCnZhciBhdXRoID0gKG1xdHRfdXJsLmF1dGggfHwgJzonKS5zcGxpdCgnOicpOw0KdmFyIHVybCA9ICJtcXR0Oi8vIiArIG1xdHRfdXJsLmhvc3Q7DQoNCnZhciBvcHRpb25zID0gew0KICAgIHBvcnQ6IG1xdHRfdXJsLnBvcnQsDQogICAgY2xpZW50SWQ6ICdtcXR0anNfJyArIE1hdGgucmFuZG9tKCkudG9TdHJpbmcoMTYpLnN1YnN0cigyLCA4KSwNCiAgICB1c2VybmFtZTogYXV0aFswXSwNCiAgICBwYXNzd29yZDogYXV0aFsxXSwNCn07DQoNCmNvbnN0IERFRkFVTFRfVkFMVUUgPSAtMjU1Ow0KdmFyIHRlbXBlcmF0dXJlID0gREVGQVVMVF9WQUxVRTsNCnZhciBodW1pZGl0eSA9IERFRkFVTFRfVkFMVUU7DQoNCmV4cG9ydHMuaGFuZGxlciA9IGZ1bmN0aW9uKGNvbnRleHQsIGV2ZW50KSB7DQogICAgdmFyIGNsaWVudCA9IG1xdHQuY29ubmVjdCh1cmwsIG9wdGlvbnMpOw0KDQogICAgY2xpZW50Lm9uKCdjb25uZWN0JywgZnVuY3Rpb24oKSB7DQogICAgICAgIGNsaWVudC5zdWJzY3JpYmUoWyJpb3Qvc2Vuc29ycy90ZW1wZXJhdHVyZSIsICJpb3Qvc2Vuc29ycy9odW1pZGl0eSJdLCBmdW5jdGlvbihlcnIpew0KICAgICAgICAgICAgaWYoZXJyKXsNCiAgICAgICAgICAgICAgICBjb25zb2xlLmVycm9yKCJFcnJvciBvbiBzdWJzY3JpYmluZy4uLiIpOw0KICAgICAgICAgICAgfQ0KICAgICAgICB9KTsNCiAgICB9KTsNCiAgICBjbGllbnQub24oJ21lc3NhZ2UnLCBmdW5jdGlvbiAodG9waWMsIG1lc3NhZ2UpIHsNCiAgICAgICAgdmFyIHRvcGljTmFtZSA9IHRvcGljLnNwbGl0KCIvIikucG9wKCk7DQogICAgICAgIA0KICAgICAgICBzd2l0Y2godG9waWNOYW1lKXsNCiAgICAgICAgICAgIC8vdGVtcGVyYXR1cmUNCiAgICAgICAgICAgIGNhc2UgU2Vuc29ycy5URU1QRVJBVFVSRToNCiAgICAgICAgICAgICAgICB0ZW1wZXJhdHVyZSA9IG1lc3NhZ2UudG9TdHJpbmcoKTsgDQogICAgICAgICAgICBicmVhazsNCiAgICAgICAgICAgIC8vaHVtaWRpdHkNCiAgICAgICAgICAgIGNhc2UgU2Vuc29ycy5IVU1JRElUWToNCiAgICAgICAgICAgICAgICBodW1pZGl0eSA9IG1lc3NhZ2UudG9TdHJpbmcoKTsNCiAgICAgICAgICAgIGJyZWFrOw0KICAgICAgICB9DQogICAgICAgIGlmKCh0ZW1wZXJhdHVyZSAhPSBERUZBVUxUX1ZBTFVFKSAmJiAoaHVtaWRpdHkgIT0gREVGQVVMVF9WQUxVRSkpew0KICAgICAgICAgICAgLy9USEkNCiAgICAgICAgICAgIHZhciB0aGlfaW5kZXggPSAoTWF0aC5mbG9vcigoKDEuOCAqIHRlbXBlcmF0dXJlKSAtICgoMSAtIChodW1pZGl0eSAvIDEwMCkpICogKHRlbXBlcmF0dXJlIC0gMTQuMykpKSArIDMyKSkudG9TdHJpbmcoKTsNCg0KICAgICAgICAgICAgY2xpZW50LnB1Ymxpc2goImlvdC9sb2dzIiwgdGhpX2luZGV4LCBmdW5jdGlvbigpew0KICAgICAgICAgICAgICAgIGNsaWVudC5lbmQoKTsNCiAgICAgICAgICAgICAgICB0ZW1wZXJhdHVyZSA9IERFRkFVTFRfVkFMVUU7DQogICAgICAgICAgICAgICAgaHVtaWRpdHkgPSBERUZBVUxUX1ZBTFVFOw0KICAgICAgICAgICAgICAgIHZhciBpbmZvcyA9ICIgVGVtcCAtPiAiKyB0ZW1wZXJhdHVyZSArICIsIEh1bWkgLT4gIiArIGh1bWlkaXR5Ow0KICAgICAgICAgICAgICAgIGNvbnRleHQuY2FsbGJhY2soJ01RVFQgdmFsdWVzIHJlY2VpdmVkLCBUSEkgOiAnICsgdGhpX2luZGV4ICsgaW5mb3MgKyAiLCBzZW5kaW5nIHRvIGxvZ3MuIik7IA0KICAgICAgICAgICAgfSk7DQogICAgICAgIH0gZWxzZSBjb25zb2xlLmxvZygiQXNwZXR0byBkYXRpIG1hbmNhbnRpLi4uIik7DQogICAgfSk7DQp9Ow==
    baseImage: "node:14-alpine"
    commands:
      - 'npm install mqtt'
    runtimeAttributes:
      repositories: []
    codeEntryType: sourceCode
  platform: {}
  readinessTimeoutSeconds: 60
